### ISSUE TITLE
How to use the MOdel?

### ISSUE THREAD

**Issue by Shubho2** [wonjininfo/CollaboNet#2]
After training how can I use the saved model for my project? Can someone explain how to use the model to predict different entities of a given text?

**Comment by wen-fei** [comment]
I meet same problems. I read the codes and have to say,   he put the training validation tests together. bad design.

**Comment by wonjininfo** [comment]
Dear wen-fei,
Unfortunately, I couldn't exactly get your mention "put the training validation tests together".

If you are mentioning "design", yes. Our code in this repository is designed only for proof of our model. Therefore we did not considered any real time use or inference-only mode.

If you are mentioning separation of dataset for training and test run of the model, which is related to academic integrity, we clearly divided test data from train and validation data.
For the latter one, we are open to discuss on this matter. Please leave comment here or send me email for further talk.

Thank you for your interest in our work.
Best regards, 
Wonjin

**Comment by wonjininfo** [comment]
Dear sub10, 
My apologize for late reply. Since we were about to publish our new paper, which we made our code more easy to use, I was delaying reply until the publication.
However our paper needed revision and I was dealing with some problems, I forgot to answer the comment. 
Once again sorry for late reply and thank you so much for your interest in our work.
With best, Wonjin

**Comment by wonjininfo** [comment]
Dear sub10,
If you prefer to use CollaboNet for inference mode, you will need to modify the code.
Current code in this repository does not support inference only mode.
Thanks

**Comment by Nicozwy** [comment]
In order to apply the CollaboNet to another datasets, what should I do?

**Comment by wonjininfo** [comment]
Hi @393301836, it looks like your comment here is a duplicated. Please see #4
