### ISSUE TITLE
How long will Single Task Model [STM] totally takes over 6 datasets?

### ISSUE THREAD

**Issue by Nicozwy** [wonjininfo/CollaboNet#3]
Hello!
It looks slowly when training, and how many times will the training repeat?? Besides,
it looks training on 6 datasets at the same time, may I just train on a single dataset? Thank you in advance.

**Comment by Nicozwy** [comment]
About 2 days on my machine

**Comment by wonjininfo** [comment]
Hello,
Yes, it takes some time to fully trained. 2 days looks fine. 
For STM, training will stop at following pre-decided epoch or early stop criteria, whichever is faster. 
```
NCBI: 24,
JNLPBA: 30,
BC2GM: 30,
BC4CHEMD: 30,
BC5CDR-chem: 25,
BC5CDR-disease: 25
```
If you want to train the model on only one dataset, you will need to adjust it using command line parameters. 
From https://github.com/wonjininfo/CollaboNet/blob/master/stm.sh , you can see  `python run.py --ncbi --jnlpba --bc5_chem --bc5_disease --bc4 --bc2 .... `.
If you only want to train on `NCBI` for example, then you can pass only `--ncbi` as command line parameter.  
Thanks!

**Comment by Nicozwy** [comment]
Thank you very much. 
It is helpful for me to evaluate the Collaborate model.
