### ISSUE TITLE
How to evaluation CollaboNet on any other dataset?

### ISSUE THREAD

**Issue by Nicozwy** [wonjininfo/CollaboNet#4]
Thanks,
From the table, the CollaboNet achieved great performance in many datasets, but I want to evaluate the CollaboNet on my own datasets. What should I do? Thank you in advance.

**Comment by wonjininfo** [comment]
Hi,
Thank you for your interest in our work. 
Our code in this repository is designed only for proof of our model. Therefore we did not consider any real-time use or make inference-only mode.
If you would like to evaluate CollaboNet on other datasets, you will need to do some additional work. 

The easiest way to train and evaluate another dataset is to pre-process your dataset into the shape of our datasets. Then change code near line #84~#111.
https://github.com/wonjininfo/CollaboNet/blob/4419de4230667938b3382b26a372c117680f8758/run.py#L84
Create new parameters and comment out codes on other datasets.
For example,
```
    if True: 
        exampledataset= deepcopy(args)
        exampledataset.guidee_data = 'NameOfExampledataset'  
        modelDict['NameOfExampledataset']={'args':exampledataset}
```
Thanks

**Comment by Nicozwy** [comment]
Thank you for your detail guidance, it is very helpful to me !
