### ISSUE TITLE
Why the evaluation result on other dataset is zero?

### ISSUE THREAD

**Issue by Nicozwy** [wonjininfo/CollaboNet#5]
[0 phase]
====TES_MODEL Training=====
== Epoch:  24 == | train time : 0 Min |
 train loss: 6.642172
====TES_MODEL Test=====
[test] Precision : 0.0000 | Recall : 0.0000 | F1: 0.0000

**Comment by Nicozwy** [comment]
I have changed my dataset as the shape of given datasets and run it successfully, however, when comes to the evaluation, all the metrics get zeros. Is the code only suitable for the 6 datasets ?

**Comment by wonjininfo** [comment]
Hi, the code works universally. Even if your dataset is not a NER dataset, you can use it with minimum modifications. 
I think there might be a point you may miss. 
However, it's a bit difficult to figure out your problem due to lack of information. 
I would recommend you to double-check your code and data, and please attach more detailed information on the problem.
Thanks!

**Comment by Nicozwy** [comment]
Thank you ! Here is my modifications:
the preprocessing.py is set as other datasets.

> #sampleData-IOB
>Path['devsetPath'] =  '../MTL-Bioinformatics-2016/data/sampleData-IOB/devel.tsv'
>Path['testsetPath'] = '../MTL-Bioinformatics-2016/data/sampleData-IOB/test.tsv'
>Path['trainsetPath'] ='../MTL-Bioinformatics-2016/data/sampleData-IOB/train.tsv'
>sentenceTuple, wordset, wordsetTD, charset = makeTup(Path)
>word2ID, ID2word, word2IDTD, ID2wordTD, char2ID, ID2char = >makeIDTup('sampleData-IOB',sentenceTuple, wordset, wordsetTD, charset, word2ID, ID2word, >word2IDTD, ID2wordTD, char2ID, ID2char)


In run.py
>      parser.add_argument('--sample', action='store_true', help='include sampledata data', default=False)

     if args.sample:
        sci_args=deepcopy(args) 
        sci_args.guidee_data='sampleData'
        modelDict['sampleData']={'args':sci_args}

By the way, I even copy the given datasets of the codes to the **sampleData** directory {train.tsv, test.tsv, devel.tsv}, which encounters the same problem.  

Is the  IOB-annotated dataset  supported by the code ??

That is all.
Thank you very much.

**Comment by Nicozwy** [comment]
In addition, if only a part data of any given dataset is applied, I can not evaluate the code successfully. For example, I take about the first 80 lines of the NCBI-disease dataset (the data of train.tsv is slightly more than others) as input, we will get the result, "
[test] Precision : 0.0000 | Recall : 0.0000 | F1: 0.0000
".
As shown above, I do nothing to the code except modifying the dataset.
Whether there are some points I may miss?? Looking forward to your response.@wonjininfo 

Thank you!

**Comment by 393301836** [comment]
11

**Comment by Nicozwy** [comment]
Hi, wonjininfo:
I have tried my best to run the code on my dataset (with  IOB-annotated ), however, there is still some problem with the output as described above. If I want to run on CoNLL2003 in [https://github.com/kyzhouhzau/BERT-NER/tree/master/data](url), what should do to avoid the problem, and can you have a try to verify. Thank you!

with regards

**Comment by wonjininfo** [comment]
Hi @zwacm , 
Our code was developed using IOB tag at the early days. You can use our code for IOB-annotated dataset as well. 
However, one of the most important parts, the evaluation part is written for IOBES-annotated dataset. You will need to modify that part if you wish to use our code for IOB datasets. 
Thanks

**Comment by Nicozwy** [comment]
Ok, thank you very much, I got it.
