### ISSUE TITLE
Error while trying to run stm.sh

### ISSUE THREAD

**Issue by youssef-snoussi** [wonjininfo/CollaboNet#7]
Hello, I've been trying to run the single task model in a docker image, the requirements are respected, as i installed python 2.7.12, numpy 1.14.2 and tensorflow-gpu 1.7.0. The error occurs when running **stm.sh** and it gives the following stack trace 

**Traceback (most recent call last):
  File "run.py", line 76, in <module>
    ID2wordVecIdx, wordVec2LineNo, wordEmbedding = input_wordVec()
  File "/home/Collabo/collabonet/CollaboNet-master/ops/inputData.py", line 35, in input_wordVec
    ID2wordVecIdx, wordVec2LineNo, wordEmbedding = wiki_wordVecProcessing(word2ID, word2IDTD)
  File "/home/Collabo/collabonet/CollaboNet-master/ops/embeddingOps.py", line 13, in wiki_wordVecProcessing
    wordVec2LineNo, wordEmbedding = wiki_loadWordVec(wordVecFilePath)
  File "/home/Collabo/collabonet/CollaboNet-master/ops/embeddingOps.py", line 43, in wiki_loadWordVec
    wordVec2LineNo['<UNK>']=itera+2
UnboundLocalError: local variable 'itera' referenced before assignment**

I have a suspicion that it has something to do with missing data as when running **download.sh** it produces not found errors 

![Screenshot from 2021-03-08 22-44-06](https://user-images.githubusercontent.com/69009221/110492042-1ce2d200-80f2-11eb-8495-5bef607f0d4e.png)

**Comment by wonjininfo** [comment]
Hello,
Sorry for the delay in getting back to you. 

Yes, it seems like the google drive system is updated and they no longer allow direct downloading from the "wget" method (at least they blocked the current script).

Let's start from there, [here is a link](https://drive.google.com/drive/folders/1EMA0sw_tl54Q53Fm-UBW3oyCqEim8-Pr?usp=sharing) to the mentioned files, which are the table of dense representations of vocabularies. 

My co-author, Chan Ho, holds original files, but I think these are identical copies of them. 
Should you have further questions, please let me!
Thanks,
Wonjin

**Comment by youssef-snoussi** [comment]
Thanks for your reply and for providing the missing files.
